# Generated by Django 5.1.1 on 2024-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0012_alter_sales_payment_choice_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='reason',
            field=models.CharField(default='Faulty', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rPyyQCxhVwOfi4aCplCp5b$OywxiRX+m7Oc2cKPpycFf3Usf9zgWZfTG715025Y7QM=', max_length=128),
        ),
    ]
