# Generated by Django 5.1.1 on 2024-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0013_returns_reason_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Yp30zUcc5elp3HIFv04ygF$Wtho6xTYSCXWDFkLkPiI8uSaAXA/0m+NyKauLScdtNU=', max_length=128),
        ),
    ]
