# Generated by Django 5.1.1 on 2024-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0014_alter_returns_reason_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Unprocessed', 'Unprocessed')], default='Unprocessed', max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$3NG1T3eLIJ1f7cLZ0waqv1$WAr8+sdcoiDUl8x32oqBJVEJNSI67qqzfuvJJsjOqwk=', max_length=128),
        ),
    ]
